/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.jgranados.ipc1_2025.poo.avanzado.threads.swing.frontend;

import java.time.LocalTime;
import java.util.Random;

/**
 *
 * @author jose
 */
public class CajeroPanel extends javax.swing.JPanel implements Runnable {
    
    private int[] productos;
    private String nombre;

    /**
     * Creates new form CajeroPanel
     */
    public CajeroPanel() {
        this.productos = generarProductos();
        this.nombre = LocalTime.now().toString();
        initComponents();
    }
    
    @Override
    public void run() {
        lblNombre.setText(nombre);
        procesarProductos();
        lblProducto.setText("Ya finalizo.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        lblProducto = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setMaximumSize(new java.awt.Dimension(100, 100));
        setMinimumSize(new java.awt.Dimension(100, 100));
        setPreferredSize(new java.awt.Dimension(100, 100));
        setRequestFocusEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    private int[] generarProductos() {
        Random random = new Random();
        int cantidad = random.nextInt(3, 8);
        int[] productos = new int[cantidad];
        
        for (int i = 0; i < productos.length; i++) {
            productos[i] = random.nextInt(2, 11);
        }
        
        return productos;
    }
    
    private void procesarProductos() {
        try {
            for (int i = 0; i < productos.length; i++) {
                int producto = productos[i];
                lblProducto.setText("Prod " + (i + 1) + ", " + producto + "seg");
                Thread.sleep(producto * 1000);
            }
        } catch (InterruptedException e) {
            // manejar correctamente el error
            e.printStackTrace();
        }

    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblProducto;
    // End of variables declaration//GEN-END:variables
}
